<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>        
        <PackageId>CSharpBrasil.Extensions.Caching.LiteDb</PackageId>
        <Version>0.1.1</Version>
        <Authors>Raphael Augusto Ferroni Cardoso</Authors>
        <Company>C# Brasil</Company>
        <Description>Implementation of IDistributedCache using LiteDB as backend storage</Description>
        <PackageProjectUrl>https://github.com/csharpbrasil/CSharpBrasil.Extensions.Caching.LiteDb</PackageProjectUrl>
        <RepositoryUrl>https://github.com/csharpbrasil/CSharpBrasil.Extensions.Caching.LiteDb</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright © 2025 C# Brasil</Copyright>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="../icon.png" Pack="true" PackagePath="" />
        <None Include="../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LiteDB" Version="5.0.21" />
      <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.4" />
    </ItemGroup>

</Project>
